services:
    kasimi.markpostunread.listener:
        class: kasimi\markpostunread\event\listener
        arguments:
            - %core.root_path%
            - %core.php_ext%
            - @user
            - @config
            - @controller.helper
            - @template
            - @kasimi.markpostunread.core
        tags:
            - { name: event.listener }
    kasimi.markpostunread.controller:
        class: kasimi\markpostunread\controller\controller
        arguments:
            - %core.root_path%
            - %core.php_ext%
            - @user
            - @controller.helper
            - @kasimi.markpostunread.core
    kasimi.markpostunread.core:
        class: kasimi\markpostunread\core
        arguments:
            - @user
            - @config
            - @auth
            - @dbal.conn
            - @content.visibility